name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
    paths:
      - "back-end/**"
      - "front-end/**"
      - ".github/workflows/build-and-push.yml"

env:
  #REGISTRY: harbor.spaasta.com
  #IMAGE_NAME: rancher/v2.11.2
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # The target repo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: read
      packages: write

    steps:
      # 1) Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_PAT }} # The PAT referenced in prerequisites
          submodules: recursive # If the repo has multiple submodules to checkout

      # 2) Log in to GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }} # This is the repo owner
          password: ${{ secrets.GITHUB_TOKEN }} # A token generated during the workflow

      ############################################################
      # Backend Image Build & Push
      ############################################################
      - name: Build backend image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/homepage-backend:v1.0 \
            ./back-end

      - name: Push backend image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/homepage-backend:v1.0

      ############################################################
      # Frontend Image Build & Push
      ############################################################
      - name: Build frontend image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/homepage-frontend:v1.0 \
            ./front-end

      - name: Push frontend image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/homepage-frontend:v1.0

